# This is a basic workflow to help you get started with Actions
# Controls when the action will run.
name: Auto UPDATE CNIP LIST
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      - name: 获取 GIT 权限
        run: |
          git config --global url."https://yume233:${{ secrets.GH_TOKEN }}@github.com".insteadOf "https://github.com"
          git config --global user.email "akiayumei@gmail.com"
          git config --global user.name "yume233"
      - name: 推送
        run: |
          git add . && git commit -m "🚀 ${{ steps.date.outputs.today }}" && git push -u;
          echo ' 更新成功！'; \
          echo "---------- MAIN ----------"
          echo ' 作业完毕。'
